# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 18:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('0', 'WAITING'), ('1', 'RUNNING'), ('2', 'FINISHED')], max_length=1)),
                ('priority', models.SmallIntegerField(default=5)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('started', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
