# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170430_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjob',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sparkjob',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparkjob',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
