# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170501_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjob',
            name='inputFile',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sparkjob',
            name='iterations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sparkjob',
            name='state',
            field=models.CharField(choices=[('2', 'FINISHED'), ('1', 'RUNNING'), ('0', 'WAITING'), ('3', 'SUSPENDED')], max_length=1),
        ),
    ]
